#ifndef DISPLAYDEFINES_H
#define DISPLAYDEFINES_H

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define SCREEN_DEPTH 32

#define DISPLAY_WIDTH (SCREEN_WIDTH)
#define DISPLAY_HEIGHT (SCREEN_HEIGHT)

#endif //DISPLAYDEFINES_H
