#define CHARSET_8X8_BMP                                                  0
#define CHARSET_16X16_BMP                                                1
#define SPLASH_BMP                                                       2
#define SPLASH_SPRITES_BMP                                               3
#define TITLE_BMP                                                        4
#define TEST_PAL                                                         5
#define DUNGEON_TILESET_OBJECTS_BMP                                      6
#define DUNGEON_TILESET_OBJECTS_BMP_SPRITES                              7
#define CHARA_HERO_BMP                                                   8
#define CHARA_HERO_BMP_SPRITES                                           9
#define CHARA_HERO_HEAL_EFFECT_BMP                                       10
#define CHARA_HERO_HEAL_EFFECT_BMP_SPRITES                               11
#define CHARA_HERO_SPELL_EFFECT_BMP                                      12
#define CHARA_HERO_SPELL_EFFECT_BMP_SPRITES                              13
#define CHARA_BAT_BMP                                                    14
#define CHARA_BAT_BMP_SPRITES                                            15
#define CHARA_GOBLIN_BMP                                                 16
#define CHARA_GOBLIN_BMP_SPRITES                                         17
#define CHARA_GOBLIN_SNIPER_BMP                                          18
#define CHARA_GOBLIN_SNIPER_BMP_SPRITES                                  19
#define CHARA_ORC_BMP                                                    20
#define CHARA_ORC_BMP_SPRITES                                            21
#define CHARA_RAT_BMP                                                    22
#define CHARA_RAT_BMP_SPRITES                                            23
#define CHARA_SLIME_BMP                                                  24
#define CHARA_SLIME_BMP_SPRITES                                          25
#define CHARA_SPIDER_BMP                                                 26
#define CHARA_SPIDER_BMP_SPRITES                                         27
#define CHARA_TROLL_BMP                                                  28
#define CHARA_TROLL_BMP_SPRITES                                          29
#define PROJECTILE_ARROW_BMP                                             30
#define PROJECTILE_ARROW_BMP_SPRITES                                     31
#define ENEMY_DEATH_BMP                                                  32
#define ENEMY_DEATH_BMP_SPRITES                                          33
#define MID_BOSS_DEATH_EXPLOSION_BMP                                     34
#define MID_BOSS_DEATH_EXPLOSION_BMP_SPRITES                             35
#define MID_BOSS_EARTH_BROWN_BMP                                         36
#define MID_BOSS_EARTH_BROWN_BMP_SPRITES                                 37
#define MID_BOSS_EARTH_PROJECTILE_BMP                                    38
#define MID_BOSS_EARTH_PROJECTILE_BMP_SPRITES                            39
#define MID_BOSS_ENERGY_BMP                                              40
#define MID_BOSS_ENERGY_BMP_SPRITES                                      41
#define MID_BOSS_ENERGY_PROJECTILE_BMP                                   42
#define MID_BOSS_ENERGY_PROJECTILE_BMP_SPRITES                           43
#define MID_BOSS_FIRE_BMP                                                44
#define MID_BOSS_FIRE_BMP_SPRITES                                        45
#define MID_BOSS_FIRE_PROJECTILE_BMP                                     46
#define MID_BOSS_FIRE_PROJECTILE_BMP_SPRITES                             47
#define MID_BOSS_WATER_BMP                                               48
#define MID_BOSS_WATER_BMP_SPRITES                                       49
#define MID_BOSS_WATER_PROJECTILE_BMP                                    50
#define MID_BOSS_WATER_PROJECTILE_BMP_SPRITES                            51
#define MAP_LAYER_BMP                                                    52
#define DEVDUNGEON_0_LEVEL_1_MAP                                         53
#define DEVDUNGEON_0_LEVEL_2_MAP                                         54
#define DEVDUNGEON_0_LEVEL_3_MAP                                         55
#define DEVDUNGEON_0_LEVEL_4_MAP                                         56
#define DUNGEON_1_LEVEL_1_MAP                                            57
#define DUNGEON_1_LEVEL_2_MAP                                            58
#define DUNGEON_1_LEVEL_3_MAP                                            59
#define DUNGEON_1_LEVEL_4_MAP                                            60
#define DUNGEON_1_LEVEL_5_MAP                                            61
#define DUNGEON_1_LEVEL_9_MAP                                            62
#define EMPTYSONG_XM                                                     63
#define COUNTRYSIDE_XM                                                   64
#define CYBERPUNK_XM                                                     65
#define GAMEOVER_XM                                                      66
#define GLACIAL_MOUNTAINS_XM                                             67
#define MAIN_MENU_XM                                                     68
#define SPAAACE_XM                                                       69
#define UNDERWATERFANTASY_XM                                             70
#define UNDER_WATER_XM                                                   71
#define ENTERCREDITS_XM                                                  72
#define SFX_ROTATE_BLOCK_RIGHT_WAV                                       73
#define SFX_ROTATE_BLOCK_LEFT_WAV                                        74
#define SFX_GOOD_DROP_BLOCK_WAV                                          75
#define SFX_BAD_DROP_BLOCK_WAV                                           76
#define SFX_MOVE_BLOCK_WAV                                               77
#define SFX_SCORE_COMBO_WAV                                              78
#define SFX_OPTION_SELECT_WAV                                            79
#define SFX_EXPLODE_BLOCK_WAV                                            80
#define SFX_NEXT_LEVEL_WAV                                               81
#define SFX_NEXT_STAGE_WAV                                               82
#define SFX_SAVE_GAME_WAV                                                83

#define NUM_RESOURCES                                                    84
